name: spark

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  repository_dispatch:
    types: [spark]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  spark:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: List files in the repository (for debugging purposes)
      - run: ls -la

      # Step 3: Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 4: Set up Java
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      # Step 5: Set up Spark
      - uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.5.3'
          hadoop-version: '3'

      # Step 6: Check Spark version
      - run: spark-submit --version
      - run: spark-submit --master local hello.py
      - run: ls -la

